export default [
  {countryname: 'Afghanistan', country_code: '+93'},
  {countryname: 'Albania', country_code: '+355'},
  {countryname: 'Algeria', country_code: '+213'},
  {countryname: 'American Samoa', country_code: '+683'},
  {countryname: 'Andorra', country_code: '+376'},
  {countryname: 'Angola', country_code: '+244'},
  {countryname: 'Anguilla', country_code: '+263'},
  {countryname: 'Antarctica', country_code: '+672'},
  {countryname: 'Antigua', country_code: '+267'},
  {countryname: 'Argentina', country_code: '+54'},
  {countryname: 'Armenia', country_code: '+374'},
  {countryname: 'Aruba', country_code: '+297'},
  {countryname: 'Ascension', country_code: '+247'},
  {countryname: 'Australia', country_code: '+61'},
  {countryname: 'Aus External', country_code: '+672'},
  {countryname: 'Austria', country_code: '+43'},
  {countryname: 'Azerbaijan', country_code: '+994'},
  {countryname: 'Bahamas', country_code: '+241'},
  {countryname: 'Bahrain', country_code: '+973'},
  {countryname: 'Bangladesh', country_code: '+880'},
  {countryname: 'Barbados', country_code: '+245'},
  {countryname: 'Barbuda', country_code: '+267'},
  {countryname: 'Belarus', country_code: '+375'},
  {countryname: 'Belgium', country_code: '+32'},
  {countryname: 'Belize', country_code: '+501'},
  {countryname: 'Benin', country_code: '+229'},
  {countryname: 'Bermuda', country_code: '+440'},
  {countryname: 'Bhutan', country_code: '+975'},
  {countryname: 'Bolivia', country_code: '+591'},
  {countryname: 'Bosnia', country_code: '+387'},
  {countryname: 'Botswana', country_code: '+267'},
  {countryname: 'Brazil', country_code: '+55'},
  {countryname: 'Brunei', country_code: '+673'},
  {countryname: 'Bulgaria', country_code: '+359'},
  {countryname: 'Burkina Faso', country_code: '+226'},
  {countryname: 'Burundi', country_code: '+257'},
  {countryname: 'Cambodia', country_code: '+855'},
  {countryname: 'Cameroon', country_code: '+237'},
  {countryname: 'Canada', country_code: '+1'},
  {countryname: 'Cape Verde Islands', country_code: '+238'},
  {countryname: 'Cayman Islands', country_code: '+344'},
  {countryname: 'Central African Republic', country_code: '+236'},
  {countryname: 'Chad', country_code: '+235'},
  {countryname: 'Chatham Island', country_code: '+64'},
  {countryname: 'Chile', country_code: '+56'},
  {countryname: 'China (PRC)', country_code: '+86'},
  {countryname: 'Colombia', country_code: '+57'},
  {countryname: 'Comoros', country_code: '+269'},
  {countryname: 'Congo', country_code: '+242'},
  {countryname: 'Congo', country_code: '+243'},
  {countryname: 'Cook Islands', country_code: '+682'},
  {countryname: 'Costa Rica', country_code: '+506'},
  {countryname: 'Ivory Coast', country_code: '+225'},
  {countryname: 'Croatia', country_code: '+385'},
  {countryname: 'Cuba', country_code: '+53'},
  {countryname: 'Cuba-Guantanamo', country_code: '+5399'},
  {countryname: 'Curaçao', country_code: '+599'},
  {countryname: 'Cyprus', country_code: '+357'},
  {countryname: 'Czech Republic', country_code: '+420'},
  {countryname: 'Denmark', country_code: '+45'},
  {countryname: 'Diego Garcia', country_code: '+246'},
  {countryname: 'Djibouti', country_code: '+253'},
  {countryname: 'Dominica', country_code: '+766'},
  {countryname: 'East Timor', country_code: '+670'},
  {countryname: 'Easter Island', country_code: '+56'},
  {countryname: 'Ecuador', country_code: '+593'},
  {countryname: 'Egypt', country_code: '+20'},
  {countryname: 'El Salvador', country_code: '+503'},
  {countryname: 'Equatorial Guinea', country_code: '+240'},
  {countryname: 'Eritrea', country_code: '+291'},
  {countryname: 'Estonia', country_code: '+372'},
  {countryname: 'Ethiopia', country_code: '+251'},
  {countryname: 'Falkland Islands', country_code: '+500'},
  {countryname: 'Faroe Islands', country_code: '+298'},
  {countryname: 'Fiji Islands', country_code: '+679'},
  {countryname: 'Finland', country_code: '+358'},
  {countryname: 'France', country_code: '+33'},
  {countryname: 'French Antilles', country_code: '+596'},
  {countryname: 'French Guiana', country_code: '+594'},
  {countryname: 'French Polynesia', country_code: '+689'},
  {countryname: 'Gabonese Republic', country_code: '+241'},
  {countryname: 'Gambia', country_code: '+220'},
  {countryname: 'Georgia', country_code: '+995'},
  {countryname: 'Germany', country_code: '+49'},
  {countryname: 'Ghana', country_code: '+233'},
  {countryname: 'Gibraltar', country_code: '+350'},
  {countryname: 'Greece', country_code: '+30'},
  {countryname: 'Greenland', country_code: '+299'},
  {countryname: 'Grenada', country_code: '+472'},
  {countryname: 'Guadeloupe', country_code: '+590'},
  {countryname: 'Guam', country_code: '+670'},
  {countryname: 'Guantanamo Bay', country_code: '+5399'},
  {countryname: 'Guatemala', country_code: '+502'},
  {countryname: 'Guinea-Bissau', country_code: '+245'},
  {countryname: 'Guinea', country_code: '+224'},
  {countryname: 'Guyana', country_code: '+592'},
  {countryname: 'Haiti', country_code: '+509'},
  {countryname: 'Honduras', country_code: '+504'},
  {countryname: 'Hong Kong', country_code: '+852'},
  {countryname: 'Hungary', country_code: '+36'},
  {countryname: 'Iceland', country_code: '+354'},
  {countryname: 'India', country_code: '+91'},
  {countryname: 'Indonesia', country_code: '+62'},
  {countryname: 'Inmarsat (East)', country_code: '+871'},
  {countryname: 'Inmarsat (West)', country_code: '+874'},
  {countryname: 'Inmarsat (Indian Ocean)', country_code: '+873'},
  {countryname: 'Inmarsat (Pacific Ocean)', country_code: '+872'},
  {countryname: 'Iran', country_code: '+98'},
  {countryname: 'Iraq', country_code: '+964'},
  {countryname: 'Ireland', country_code: '+353'},
  {countryname: 'Israel', country_code: '+972'},
  {countryname: 'Italy', country_code: '+39'},
  {countryname: 'Jamaica', country_code: '+875'},
  {countryname: 'Japan', country_code: '+81'},
  {countryname: 'Jordan', country_code: '+962'},
  {countryname: 'Kazakhstan', country_code: '+7'},
  {countryname: 'Kenya', country_code: '+254'},
  {countryname: 'Kiribati', country_code: '+686'},
  {countryname: 'Korea (North)', country_code: '+850'},
  {countryname: 'Korea (South)', country_code: '+82'},
  {countryname: 'Kuwait', country_code: '+965'},
  {countryname: 'Kyrgyz Republic', country_code: '+996'},
  {countryname: 'Laos', country_code: '+856'},
  {countryname: 'Latvia', country_code: '+371'},
  {countryname: 'Lebanon', country_code: '+961'},
  {countryname: 'Lesotho', country_code: '+266'},
  {countryname: 'Liberia', country_code: '+231'},
  {countryname: 'Libya', country_code: '+218'},
  {countryname: 'Liechtenstein', country_code: '+423'},
  {countryname: 'Lithuania', country_code: '+370'},
  {countryname: 'Luxembourg', country_code: '+352'},
  {countryname: 'Macao', country_code: '+853'},
  {countryname: 'Macedonia', country_code: '+389'},
  {countryname: 'Madagascar', country_code: '+261'},
  {countryname: 'Malawi', country_code: '+265'},
  {countryname: 'Malaysia', country_code: '+60'},
  {countryname: 'Maldives', country_code: '+960'},
  {countryname: 'Mali Republic', country_code: '+223'},
  {countryname: 'Malta', country_code: '+356'},
  {countryname: 'Marshall Islands', country_code: '+692'},
  {countryname: 'Martinique', country_code: '+596'},
  {countryname: 'Mauritania', country_code: '+222'},
  {countryname: 'Mauritius', country_code: '+230'},
  {countryname: 'Mayotte Island', country_code: '+269'},
  {countryname: 'Mexico', country_code: '+52'},
  {countryname: 'Micronesia', country_code: '+691'},
  {countryname: 'Midway Island', country_code: '+807'},
  {countryname: 'Moldova', country_code: '+373'},
  {countryname: 'Monaco', country_code: '+377'},
  {countryname: 'Mongolia', country_code: '+976'},
  {countryname: 'Montenegro', country_code: '+382'},
  {countryname: 'Montserrat', country_code: '+663'},
  {countryname: 'Morocco', country_code: '+212'},
  {countryname: 'Mozambique', country_code: '+258'},
  {countryname: 'Myanmar', country_code: '+95'},
  {countryname: 'Namibia', country_code: '+264'},
  {countryname: 'Nauru', country_code: '+674'},
  {countryname: 'Nepal', country_code: '+977'},
  {countryname: 'Netherlands', country_code: '+31'},
  {countryname: 'Netherlands Antilles', country_code: '+599'},
  {countryname: 'Nevis', country_code: '+868'},
  {countryname: 'New Caledonia', country_code: '+687'},
  {countryname: 'New Zealand', country_code: '+64'},
  {countryname: 'Nicaragua', country_code: '+505'},
  {countryname: 'Niger', country_code: '+227'},
  {countryname: 'Nigeria', country_code: '+234'},
  {countryname: 'Niue', country_code: '+683'},
  {countryname: 'Norfolk Island', country_code: '+672'},
  {countryname: 'Norway', country_code: '+47'},
  {countryname: 'Oman', country_code: '+968'},
  {countryname: 'Pakistan', country_code: '+92'},
  {countryname: 'Palau', country_code: '+680'},
  {countryname: 'Palestinian Settlements', country_code: '+970'},
  {countryname: 'Panama', country_code: '+507'},
  {countryname: 'Papua New Guinea', country_code: '+675'},
  {countryname: 'Paraguay', country_code: '+595'},
  {countryname: 'Peru', country_code: '+51'},
  {countryname: 'Philippines', country_code: '+63'},
  {countryname: 'Poland', country_code: '+48'},
  {countryname: 'Portugal', country_code: '+351'},
  {countryname: 'Qatar', country_code: '+974'},
  {countryname: 'Réunion Island', country_code: '+262'},
  {countryname: 'Romania', country_code: '+40'},
  {countryname: 'Russia', country_code: '+7'},
  {countryname: 'Rwandese Republic', country_code: '+250'},
  {countryname: 'St. Helena', country_code: '+290'},
  {countryname: 'St. Kitts/Nevis', country_code: '+868'},
  {countryname: 'St. Lucia', country_code: '+757'},
  {countryname: 'St. Pierre & Miquelon', country_code: '+508'},
  {countryname: 'St. Vincent & Grenadines', country_code: '+783'},
  {countryname: 'Samoa', country_code: '+685'},
  {countryname: 'San Marino', country_code: '+378'},
  {countryname: 'São Tomé and Principe', country_code: '+239'},
  {countryname: 'Saudi Arabia', country_code: '+966'},
  {countryname: 'Senegal', country_code: '+221'},
  {countryname: 'Serbia', country_code: '+381'},
  {countryname: 'Seychelles Republic', country_code: '+248'},
  {countryname: 'Sierra Leone', country_code: '+232'},
  {countryname: 'Singapore', country_code: '+65'},
  {countryname: 'Slovak Republic', country_code: '+421'},
  {countryname: 'Slovenia', country_code: '+386'},
  {countryname: 'Solomon Islands', country_code: '+677'},
  {countryname: 'Somali Democratic Republic', country_code: '+252'},
  {countryname: 'South Africa', country_code: '+27'},
  {countryname: 'Spain', country_code: '+34'},
  {countryname: 'Sri Lanka', country_code: '+94'},
  {countryname: 'Sudan', country_code: '+249'},
  {countryname: 'Suriname', country_code: '+597'},
  {countryname: 'Swaziland', country_code: '+268'},
  {countryname: 'Sweden', country_code: '+46'},
  {countryname: 'Switzerland', country_code: '+41'},
  {countryname: 'Syria', country_code: '+963'},
  {countryname: 'Taiwan', country_code: '+886'},
  {countryname: 'Tajikistan', country_code: '+992'},
  {countryname: 'Tanzania', country_code: '+255'},
  {countryname: 'Thailand', country_code: '+66'},
  {countryname: 'Thuraya', country_code: '+88216'},
  {countryname: 'Timor Leste', country_code: '+670'},
  {countryname: 'Togolese Republic', country_code: '+228'},
  {countryname: 'Tokelau', country_code: '+690'},
  {countryname: 'Tonga Islands', country_code: '+676'},
  {countryname: 'Trinidad & Tobago', country_code: '+867'},
  {countryname: 'Tunisia', country_code: '+216'},
  {countryname: 'Turkey', country_code: '+90'},
  {countryname: 'Turkmenistan', country_code: '+993'},
  {countryname: 'Turks and Caicos Islands', country_code: '+648'},
  {countryname: 'Tuvalu', country_code: '+688'},
  {countryname: 'Uganda', country_code: '+256'},
  {countryname: 'Ukraine', country_code: '+380'},
  {countryname: 'United Arab Emirates', country_code: '+971'},
  {countryname: 'United Kingdom', country_code: '+44'},
  {countryname: 'United States of America', country_code: '+1'},
  {countryname: 'US Virgin Islands', country_code: '+339'},
  {countryname: 'Uruguay', country_code: '+598'},
  {countryname: 'Uzbekistan', country_code: '+998'},
  {countryname: 'Vanuatu', country_code: '+678'},
  {countryname: 'Venezuela', country_code: '+58'},
  {countryname: 'Vietnam', country_code: '+84'},
  {countryname: 'Wake Island', country_code: '+808'},
  {countryname: 'Yemen', country_code: '+967'},
  {countryname: 'Zambia', country_code: '+260'},
  {countryname: 'Zanzibar', country_code: '+255'},
  {countryname: 'Zimbabwe', country_code: '+263'},
];
